sonar.projectKey=green-juice-hub
sonar.projectName=Green Juice Hub
sonar.sourceEncoding=UTF-8
sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test,e2e/tests
sonar.java.binaries=backend/target/classes
sonar.java.test.binaries=backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.exclusions=frontend/node_modules/**,frontend/dist/**,e2e/node_modules/**,e2e/output/**
